from recommend import load_movies_from_file
from json import load
from sys import argv
from argparse import ArgumentParser


def get_args():
    parser = ArgumentParser()
    parser.add_argument('query', 
            help='part of the title to search (case-insensitive)')
    parser.add_argument('-i', '--infile', type=str, default='movies.json',
                        help='input file as generated by fetch.py')
    args = parser.parse_args()

    return args


if __name__ == '__main__':
    args = get_args()

    movies = load_movies_from_file(args.infile)
    if movies is None:
        exit('File\'s not found.')

    res = [key for key in movies if args.query.lower() in key.lower()]
    
    message = 'Results:' if len(res) != 0 else 'Nothing was found.'
    print(message)
    for movie_title in res:
        print(movie_title)
